### ISSUE TITLE
同一演员被翻译成不同中文名字

### ISSUE THREAD

**Issue by cyyhou** [sleikang/MediaServerTools#26]
环境：
群晖docker，
nyanmikas/jellyfin，10.8.6
nas-tools，2.4.2

如图，斯嘉丽约翰逊会被翻译成两个不同的中文名字，这种是哪方面的问题呢？
顺便感谢大佬支持jellyfin！

![ef112c145fa19d48e3fda84bf376f14](https://user-images.githubusercontent.com/114082073/203461195-b3573509-0d5f-4ed5-a668-7f164fa58811.jpg)
![f4b2a9eb6262e1c637ba6cadb896ee4](https://user-images.githubusercontent.com/114082073/203461194-2d7649c2-fe03-457d-be67-5f26932a63c2.jpg)

**Comment by sleikang** [comment]
这个是tmdb里又名 如果有多个含中文又名的时候我没法具体去区分哪个是正确的，而且又名是可以随意更改的，这个是没法保持一致性的
