### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by iranee** [sleikang/MediaServerTools#27]
获取TMDB媒体ID[None]季ID[1]信息失败, 异常错误：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/tv/None/season/1?api_key=******************&language=zh-SG&append_to_response=alternative_titles (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ca818b5b0>: Failed to establish a new connection: [Errno 101] Network unreachable'))

更换了api也是这样提示，配置文件没有更改，跟之前的一样，正常工作了一周，这两天提示这个

**Comment by sleikang** [comment]
这是tmdb连不上，请自行检查代理
