### ISSUE TITLE
每一季的人物不会更新

### ISSUE THREAD

**Issue by shanyan-wcx** [sleikang/MediaServerTools#32]
![屏幕截图_20221128_104306](https://user-images.githubusercontent.com/58252651/204180296-658a0730-8eee-456c-bf2c-ab3cdd156f54.png)
就是第几季点进去所有集数下方的演员不更新。

**Comment by sleikang** [comment]
![image](https://user-images.githubusercontent.com/23020770/204413298-f4c2ac71-7c2b-482e-9634-149391c04f91.png)

**Comment by sleikang** [comment]
已经更新 这个季信息只有Jellyfin有演员，Emby都是没有的
