### ISSUE TITLE
系列中的电影不会更新人物

### ISSUE THREAD

**Issue by shanyan-wcx** [sleikang/MediaServerTools#33]
![屏幕截图_20221128_030358](https://user-images.githubusercontent.com/58252651/204214705-3f73d16e-bada-4f6d-bb72-62b3f125a5c8.png)

**Comment by sleikang** [comment]
这是合集，合集里面有的视频实际媒体库都有，所以我屏蔽了合集，除非你把合集不显示在实际媒体库文件夹

**Comment by shanyan-wcx** [comment]
![屏幕截图_20221129_105013](https://user-images.githubusercontent.com/58252651/204426740-dfad95cb-f4f0-486a-a41f-5e225164c0d8.png)
我的媒体库是这样子的，同一合集的电影合并在一起，合集里的电影不会更新啊
