### ISSUE TITLE
一直获取jellyfin人物信息失败

### ISSUE THREAD

**Issue by shanyan-wcx** [sleikang/MediaServerTools#34]
![屏幕截图_20221130_025401](https://user-images.githubusercontent.com/58252651/204728198-6ebbb63e-697d-4c0e-b9cf-da8453949cfc.png)

**Comment by sleikang** [comment]
这种是配置问题自己检查，检查配置是否正常，检查jellyfin是否为最新版

**Comment by shanyan-wcx** [comment]
jellyfin是10.8.6中国特供版，配置应该没问题呀，刚开始运行的时候是正常的，运行几分钟后才开始出现获取失败
