### ISSUE TITLE
多个季度的信息全部被替换成了第一季的信息

### ISSUE THREAD

**Issue by ltsj** [sleikang/MediaServerTools#36]
![image](https://user-images.githubusercontent.com/30733960/207775093-5fe1f411-3f49-4609-9ae3-fd4f5468f98d.png)
![image](https://user-images.githubusercontent.com/30733960/207775114-14464b5f-bc9c-41b6-8dcf-d1ba6657c552.png)
![image](https://user-images.githubusercontent.com/30733960/207775132-b3943be0-e77e-45d2-8338-98a155e9493c.png)
![image](https://user-images.githubusercontent.com/30733960/207775145-1e5e468f-d569-4372-94ad-abfa054bf72c.png)
其他几个季度也是如此 不仅仅是这一部剧...

**Comment by kuroyukihime0** [comment]
最新出现了同样的问题。可复现，
蛇蝎美人第二季，应召女友第2。3季 都可以复现

**Comment by sleikang** [comment]
![image](https://user-images.githubusercontent.com/23020770/209348575-aafded4b-3777-44c8-b677-fd2d4027d129.png)
![image](https://user-images.githubusercontent.com/23020770/209348627-185f546f-b1d4-46c3-b03b-659a4996882e.png)
考虑下是否是本身剧集的命名问题 我这边是正常

**Comment by kuroyukihime0** [comment]
> ![image](https://user-images.githubusercontent.com/23020770/209348575-aafded4b-3777-44c8-b677-fd2d4027d129.png) ![image](https://user-images.githubusercontent.com/23020770/209348627-185f546f-b1d4-46c3-b03b-659a4996882e.png) 考虑下是否是本身剧集的命名问题 我这边是正常

复现流程：
新建了一个emby server，并按照常规命名创建了一个空的媒体文件S02E01
![image](https://user-images.githubusercontent.com/7975549/209785749-893e6518-4785-4234-baf3-41772175242f.png)
使用emby导入刮削后正常显示，元数据和封面信息正常：
![image](https://user-images.githubusercontent.com/7975549/209785884-3756a820-e365-4702-9b7c-a978275d0a28.png)
![image](https://user-images.githubusercontent.com/7975549/209785918-14d30bc3-7ac2-4eff-8d04-06a651c6e8a8.png)

配置MediaTools进行刷新后，变成了S01E01的图片和数据：
![image](https://user-images.githubusercontent.com/7975549/209786147-2d229ad3-bbd8-4d87-bd0a-7c49c22c7180.png)
![image](https://user-images.githubusercontent.com/7975549/209786273-1b51dc00-c1e1-44ea-a918-283dcc3e724a.png)

**Comment by kuroyukihime0** [comment]
补充：测试了一下1.1.7版本不会有这个问题，应该是近期版本引入的

**Comment by ltsj** [comment]
核实确实是海贼王 这部剧的问题 他从第二季开始后的每一季度都不是从第一集开始的 楼上的就不清楚了 tmdb看起来是正常的
