### ISSUE TITLE
部分剧集2，3季概述和图片被替换成第1季

### ISSUE THREAD

**Issue by kuroyukihime0** [sleikang/MediaServerTools#39]
出现概率不高，但是特定剧集的特定季必现，我库里发现的有蛇蝎美人第2季，应召女友第2，3季，嗜血法医第8季

复现流程：
1.新建了一个全新的emby server，并按照常规命名创建了一个空的媒体文件S02E01
![image](https://user-images.githubusercontent.com/7975549/212467726-96471c8a-e804-40c2-b761-77fdd2f370df.png)

2.使用emby创建媒体库，导入刮削后，元数据和封面信息正常：
![image](https://user-images.githubusercontent.com/7975549/212467735-73b60b51-1478-4b17-9273-7f28552969cf.png)
![image](https://user-images.githubusercontent.com/7975549/212467741-263a243a-5cf1-45ac-b2d0-ab676f00cfbb.png)

3.配置MediaTools进行刷新后，可以看到该集变成了S01E01的图片和数据：
![image](https://user-images.githubusercontent.com/7975549/212467767-e20347fe-0f3c-42e4-a1b7-b55ab3150e3a.png)
![image](https://user-images.githubusercontent.com/7975549/212467770-99dba107-68f3-40c3-a179-cb6f7bd3b7af.png)

**Comment by Tasle** [comment]
是的，同样遇到过

**Comment by sleikang** [comment]
这种是在你剧集收集不完整下才会出现，请按顺序收录即可，因为接口根据Index获取季号，如果只放了S02可能媒体服务器把S02的Index标记为1
![image](https://user-images.githubusercontent.com/23020770/215369144-829c83d8-46c6-42ed-8ffe-be45bedc918d.png)

**Comment by kuroyukihime0** [comment]
> 这种是在你剧集收集不完整下才会出现，请按顺序收录即可，因为接口根据Index获取季号，如果只放了S02可能媒体服务器把S02的Index标记为1 ![image](https://user-images.githubusercontent.com/23020770/215369144-829c83d8-46c6-42ed-8ffe-be45bedc918d.png)



**-你好，我库里的剧集是收集齐全的并且出问题的，之前贴的流程只是为了方便测试。**

我重新添加下收集齐全的情况：
1.全集常规命名，并经过emby刮削后和tmdb信息一致：
![image](https://user-images.githubusercontent.com/7975549/215380826-be5ec722-bca6-44d8-935b-78279e5e3fb3.png)
![image](https://user-images.githubusercontent.com/7975549/215380689-d96e6530-fa5f-46fb-92e1-686b244df54d.png)
![image](https://user-images.githubusercontent.com/7975549/215380848-baf544a7-0403-4a01-b17a-882ebe67e236.png)
![image](https://user-images.githubusercontent.com/7975549/215380620-b5c03f90-521c-4366-b01e-5ada79fdbbf6.png)



2.启动脚本刷新，可以发现脚本还是替换了2/3季的所有图片和简介
![image](https://user-images.githubusercontent.com/7975549/215381751-4cab8f92-10ae-445a-9d96-864c110cc43b.png)


进入Emby,可以发现所有2/3季元数据被替换成1季的
![image](https://user-images.githubusercontent.com/7975549/215381894-f9bfff1a-7f09-451b-a734-7b84827fc1ac.png)
![image](https://user-images.githubusercontent.com/7975549/215381919-bdea9604-4524-42b4-a810-15c1b5e1262a.png)
![image](https://user-images.githubusercontent.com/7975549/215381939-d6f6d4c4-2f57-4c36-959a-e15b8e01f84b.png)
