### ISSUE TITLE
代理问题

### ISSUE THREAD

**Issue by qiuzhangsaer** [sleikang/MediaServerTools#47]
可以加个代理设置吗，docker下不好操作

**Comment by sleikang** [comment]
可以路由器开代理，电脑本身开代理不是一个好的方案，路由器可以使用openwrt系统，一些代理插件比较完善，支持跳过国内ip只代理国外规则等

**Comment by ArthurSmoke** [comment]
这个需求，创建docker的时候添加 
-e HTTP_PROXY=Host:IP
就可以了吧
