### ISSUE TITLE
能不能跳过已上锁的内容

### ISSUE THREAD

**Issue by PoiYuudachi** [sleikang/MediaServerTools#48]

**Comment by AuroraIO** [comment]
同求，在使用MST刮削数据后番剧ISLAND被改名成了夏岛悬疑，但是B站和人们更熟悉的名字都是ISLAND，所以我不得不在MST刮削完成后又将ISLAND的名字改回去。

**Comment by sleikang** [comment]
上锁不太好排除，因为软件自身刮削一次也会上锁，如果排除那么刮一次后面都挂不了，有时间我会加个指定排除列表
