### ISSUE TITLE
支持tmdb的外语名替换成豆瓣中文名

### ISSUE THREAD

**Issue by huangzlin9** [sleikang/MediaServerTools#57]
可以的话 麻烦添加这个功能

**Comment by sleikang** [comment]
这个功能本来就支持 只不过不支持配置优先级，默认先获取TMDB的中文名称，如果没有则获取豆瓣的

**Comment by huangzlin9** [comment]
> 这个功能本来就支持 只不过不支持配置优先级，默认先获取TMDB的中文名称，如果没有则获取豆瓣的

好像没有，我的日本电影比较多 挺多在TMDB是日文名，没有转换过来，是要使用自己账号的豆瓣API KEY？

**Comment by huangzlin9** [comment]
> 这个功能本来就支持 只不过不支持配置优先级，默认先获取TMDB的中文名称，如果没有则获取豆瓣的

我的日本电影比较多，在TMDB是日文原名，没有转换过来，是要使用自己账号的豆瓣API KEY？
