### ISSUE TITLE
日志报错：获取TMDB信息失败

### ISSUE THREAD

**Issue by yotsubar** [sleikang/MediaServerTools#64]
主要是番剧。以下截取部分经过验证，在TMDB中是存在对应信息，但却报错的日志。
`2023-07-26 14:57:31,263 INFO: 获取TMDB媒体[南家三姐妹]ID[56354]季ID[4]信息失败, 文件[/MediaServerTools/api/tmdb.py]行[148]异常错误：Expecting value: line 1 column 1 (char 0)`
`2023-07-26 15:05:57,090 INFO: 获取TMDB媒体[这样算是僵尸吗？]ID[38420]季ID[2]信息失败, 文件[/MediaServerTools/api/tmdb.py]行[148]异常错误：Expecting value: line 1 column 1 (char 0)`
`2023-07-26 15:08:32,947 INFO: 获取TMDB媒体[黑礁]ID[12598]季ID[1]信息失败, 文件[/MediaServerTools/api/tmdb.py]行[148]异常错误：Expecting value: line 1 column 1 (char 0)`
发现过程：
最早是在其它电影中发现有部分演员名称还是英文，查看日志发现有类似报错，
`2023-07-26 14:46:18,678 INFO: 获取TMDB人物[Shunichi Yoshizawa]ID[2148653]信息失败, 文件[/MediaServerTools/api/tmdb.py]行[148]异常错误：Expecting value: line 1 column 1 (char 0)`
但检查后发现是TMDB里边就没有这个人。
同时发现有很多季信息失败的日志，但这些季集信息在TMDB里边都是有的。

**Comment by sleikang** [comment]
这个都是与服务API通信失败问题
