### ISSUE TITLE
中文扮演怎么配置

### ISSUE THREAD

**Issue by paysenyu** [sleikang/MediaServerTools#66]
请问中文扮演如何配置

system:
  checkmediasearch: true
  delnotimagepeople: false
  mediaserver: Emby
  seasongroup:
  - "\u7EB8\u623F\u5B50|62ed7ac87d5504007e4ab046"
  taskdonespace: 1
  threadnum: 1
  updateoverview: true
  updatepeople: true
  updateseasongroup: false
  updatetime: 1

![telegram-cloud-photo-size-5-6258240978246809498-y](https://github.com/sleikang/MediaServerTools/assets/51367628/75859e5c-1305-4e15-b274-a679d89dc9d3)

演员名字都自动更正了，但是扮演的角色还是英文的，我看介绍是有写中文扮演

**Comment by daixuan201** [comment]
我这也碰到了，怎么处理的呢？
