### ISSUE TITLE
日志里面看他是谁已经媒体完成了，但怎么不改集的标题名称 其他剧集也都是这样

### ISSUE THREAD

**Issue by jagernb** [sleikang/MediaServerTools#68]
![image](https://github.com/sleikang/MediaServerTools/assets/105163570/53379940-f072-4768-9d78-21c492727d3f)

**Comment by sleikang** [comment]
标题默认是不会检测的，只会检测剧集概要是否为中文

**Comment by jagernb** [comment]
好的，感谢解答
