### ISSUE TITLE
希望支持plex

### ISSUE THREAD

**Issue by xheia** [sleikang/MediaServerTools#77]
希望支持plex

**Comment by jiezaizone** [comment]
同上，期待能够支持plex

**Comment by x1ao4** [comment]
Emby 和 Jellyfin 刮削后会生成 NFO 文件，这个工具是去修改的这个 NFO 文件。而 Plex 刮削后并不会生成 NFO 文件，所以这个工具无法去修改数据，除非你的文件自带了 NFO，然后此工具要能访问到那个 NFO 以及有权修改，才能修改 NFO 数据，而且你还需要配合 XBMCnfoMoviesImporter 和 XBMCnfoTVImporter 才能读取到这些 NFO 的数据。

**Comment by sleikang** [comment]
plex支持的 但是下面2个由于没有接口没法实现
中文人名(Plex暂时不支持)
中文扮演(Plex暂时不支持)
