### ISSUE TITLE
群晖7.2的docker容器日志未显示

### ISSUE THREAD

**Issue by HuntzzZ** [sleikang/MediaServerTools#79]
能不能让群晖的docker容器正常显示日志，而不是想看的时候只能用file station的容器conf
ig目录下查看log.txt
![微信截图_20231017171723](https://github.com/sleikang/MediaServerTools/assets/89286461/ee368edb-a434-4869-bf92-f12db54223f4)

**Comment by cnfjice** [comment]
用portainer看

**Comment by sleikang** [comment]
新版docker群晖正常
